namespace QuizUp.DAL.Data;

public static class RandomData
{
    public record UserData(string Username, string Email, string Password);

    public record QuizData(string Title, QuestionData[] Questions);

    public record QuestionData(string QuestionText, int TimeLimit, AnswerData[] Answers);

    public record AnswerData(string AnswerText, Boolean IsCorrect);

    // generated by ChatGPT
    public static readonly UserData[] UsersData =
    [
        new ("bookworm123", "pavel.novak@seznam.cz", "someRandomPassword123"),
        new ("techgeek99", "jane.doe@gmail.com", "TechGeek*456"),
        new ("traveler7", "john.smith@outlook.com", "Travel@789"),
        new ("foodie256", "mary.jones@gmail.com", "FoodLover!321"),
        new ("naturelover", "alice.green@earthmail.com", "NatureLover!987"),
        new ("gamerzlife", "michael.brown@gaminghub.com", "GamerLife123"),
        new ("fitnessguru", "sarah.lee@fitworld.com", "FitGuru2021"),
        new ("musicmaven", "emily.white@tunemail.com", "MusicMaven$567"),
        new ("artistic_soul", "chris.jones@artlover.com", "ArtLover@456"),
        new ("moviebuff", "linda.davis@moviefan.com", "MovieBuff*789")
    ];

    // generated by ChatGPT
    public static QuizData[] QuizzesData =
    [
        new ("Intro to Quantum Physics",
            [
                new ("When was quantum physics founded?", 20,
                    [
                        new ("1900", true),
                        new ("1800", false),
                        new ("1750", false),
                        new ("2000", false)
                    ]
                ),
                new ("Who is considered the father of quantum mechanics?", 30,
                    [
                        new ("Max Planck", true),
                        new ("Albert Einstein", false),
                        new ("Isaac Newton", false),
                        new ("Niels Bohr", false)
                    ]
                ),
                new ("What principle is central to quantum mechanics?", 10,
                    [
                        new ("Uncertainty Principle", true),
                        new ("Relativity", false),
                        new ("Gravitational Force", false),
                        new ("Conservation of Energy", false)
                    ]
                ),
                new ("Which particle is the carrier of the electromagnetic force?", 20,
                    [
                        new ("Photon", true),
                        new ("Electron", false),
                        new ("Neutron", false),
                        new ("Proton", false)
                    ]
                )
            ]
        ),
        new ("Advanced JavaScript Techniques",
            [
                new ("What is a closure in JavaScript?", 20,
                    [
                        new ("A function with preserved data", true),
                        new ("An object with methods", false),
                        new ("A loop structure", false),
                        new ("A type of variable", false)
                    ]
                ),
                new ("Which method is used to parse a JSON string?", 10,
                    [
                        new ("JSON.parse()", true),
                        new ("JSON.stringify()", false),
                        new ("JSON.decode()", false),
                        new ("JSON.convert()", false)
                    ]
                ),
                new ("What does 'this' keyword refer to?", 30,
                    [
                        new ("Current execution context", true),
                        new ("Global object", false),
                        new ("Parent function", false),
                        new ("Previous scope", false)
                    ]
                ),
                new ("Which operator is used to assign a value to a variable?", 10,
                    [
                        new ("=", true),
                        new ("==", false),
                        new ("===", false),
                        new ("!==", false)
                    ]
                ),
                new ("Which method is used to add elements to an array?", 20,
                    [
                        new ("push()", true),
                        new ("pop()", false),
                        new ("shift()", false),
                        new ("unshift()", false)
                    ]
                )
            ]
        ),
        new ("History of the Roman Empire",
            [
                new ("Who was the first emperor of Rome?", 10,
                    [
                        new ("Augustus", true),
                        new ("Julius Caesar", false),
                        new ("Nero", false),
                        new ("Caligula", false)
                    ]
                ),
                new ("What was the primary language of the Roman Empire?", 20,
                    [
                        new ("Latin", true),
                        new ("Greek", false),
                        new ("Italian", false),
                        new ("Roman", false)
                    ]
                ),
                new ("Which structure is known as a Roman amphitheater?", 30,
                    [
                        new ("Colosseum", true),
                        new ("Pantheon", false),
                        new ("Parthenon", false),
                        new ("Forum", false)
                    ]
                ),
                new ("Which Roman emperor built a massive wall across Northern Britain in 122 AD?", 20,
                    [
                        new ("Hadrian", true),
                        new ("Trajan", false),
                        new ("Nero", false),
                        new ("Augustus", false)
                    ]
                )
            ]
        ),
        new ("Mastering Python",
            [
                new ("What is the keyword to define a function in Python?", 10,
                    [
                        new ("def", true),
                        new ("func", false),
                        new ("function", false),
                        new ("define", false)
                    ]
                ),
                new ("Which of the following is a Python data type?", 20,
                    [
                        new ("List", true),
                        new ("Set", true),
                        new ("Dictionary", true),
                        new ("Array", false)
                    ]
                ),
                new ("What does the 'len()' function do?", 30,
                    [
                        new ("Returns the length of an object", true),
                        new ("Returns the data type", false),
                        new ("Returns a new list", false),
                        new ("Returns the sum of elements", false)
                    ]
                ),
                new ("What is a correct syntax to output 'Hello World' in Python?", 10,
                    [
                        new ("print('Hello World')", true),
                        new ("echo 'Hello World'", false),
                        new ("printf('Hello World')", false),
                        new ("console.log('Hello World')", false)
                    ]
                ),
                new ("Which of the following is used to define a block of code in Python?", 20,
                    [
                        new ("Indentation", true),
                        new ("Brackets", false),
                        new ("Parentheses", false),
                        new ("Curly braces", false)
                    ]
                )
            ]
        ),
        new ("Basics of Digital Marketing",
            [
                new ("What is SEO?", 10,
                    [
                        new ("Search Engine Optimization", true),
                        new ("Social Engagement Operation", false),
                        new ("Secure Email Organization", false),
                        new ("Service Engine Optimization", false)
                    ]
                ),
                new ("What is a common social media platform for marketing?", 20,
                    [
                        new ("Facebook", true),
                        new ("LinkedIn", true),
                        new ("Twitter", true),
                        new ("MySpace", false)
                    ]
                ),
                new ("What is PPC advertising?", 30,
                    [
                        new ("Pay-Per-Click", true),
                        new ("Public-Private Collaboration", false),
                        new ("Paid Publicity Campaign", false),
                        new ("Pay-Per-Cost", false)
                    ]
                ),
                new ("What is the purpose of content marketing?", 20,
                    [
                        new ("To create and distribute valuable content", true),
                        new ("To create spam emails", false),
                        new ("To hack competitors' websites", false),
                        new ("To generate automatic content", false)
                    ]
                ),
                new ("Which of the following is an example of an email marketing platform?", 10,
                    [
                        new ("MailChimp", true),
                        new ("Google Analytics", false),
                        new ("Hootsuite", false),
                        new ("Salesforce", false)
                    ]
                )
            ]
        ),
        new ("Art of Storytelling",
            [
                new ("What is a protagonist?", 10,
                    [
                        new ("Main character", true),
                        new ("Narrator", false),
                        new ("Villain", false),
                        new ("Supporting character", false)
                    ]
                ),
                new ("What is a narrative arc?", 20,
                    [
                        new ("Structure of a story", true),
                        new ("Introduction of characters", false),
                        new ("Dialogue between characters", false),
                        new ("Setting of the story", false)
                    ]
                ),
                new ("Who is the author of '1984'?", 30,
                    [
                        new ("George Orwell", true),
                        new ("Aldous Huxley", false),
                        new ("J.R.R. Tolkien", false),
                        new ("Ray Bradbury", false)
                    ]
                ),
                new ("What is the climax of a story?", 20,
                    [
                        new ("The turning point of the story", true),
                        new ("The beginning of the story", false),
                        new ("The end of the story", false),
                        new ("The introduction of characters", false)
                    ]
                ),
                new ("What is the resolution of a story?", 10,
                    [
                        new ("The conclusion of the story", true),
                        new ("The conflict of the story", false),
                        new ("The rising action", false),
                        new ("The falling action", false)
                    ]
                )
            ]
        ),
        new ("World Geography Challenge",
            [
                new ("What is the capital of France?", 10,
                    [
                        new ("Paris", true),
                        new ("London", false),
                        new ("Berlin", false),
                        new ("Madrid", false)
                    ]
                ),
                new ("Which continent is the Sahara Desert in?", 20,
                    [
                        new ("Africa", true),
                        new ("Asia", false),
                        new ("Australia", false),
                        new ("South America", false)
                    ]
                ),
                new ("What is the largest ocean on Earth?", 30,
                    [
                        new ("Pacific Ocean", true),
                        new ("Atlantic Ocean", false),
                        new ("Indian Ocean", false),
                        new ("Arctic Ocean", false)
                    ]
                ),
                new ("Which country has the most natural lakes?", 20,
                    [
                        new ("Canada", true),
                        new ("Brazil", false),
                        new ("Russia", false),
                        new ("United States", false)
                    ]
                ),
                new ("Which river is the longest in the world?", 10,
                    [
                        new ("Nile", true),
                        new ("Amazon", false),
                        new ("Yangtze", false),
                        new ("Mississippi", false)
                    ]
                ),
                new ("Which country is the smallest in the world?", 20,
                    [
                        new ("Vatican City", true),
                        new ("Monaco", false),
                        new ("Nauru", false),
                        new ("San Marino", false)
                    ]
                )
            ]
        ),
        new ("Cybersecurity Fundamentals",
            [
                new ("What does 'phishing' mean?", 10,
                    [
                        new ("Fraudulent attempt to obtain sensitive information", true),
                        new ("Illegal hacking of servers", false),
                        new ("Malware infection", false),
                        new ("Data encryption process", false)
                    ]
                ),
                new ("What is a firewall used for?", 20,
                    [
                        new ("Network security", true),
                        new ("Internet speed", false),
                        new ("Data storage", false),
                        new ("Software installation", false)
                    ]
                ),
                new ("Which is a strong password?", 30,
                    [
                        new ("P@ssw0rd!", true),
                        new ("123456", false),
                        new ("password", false),
                        new ("qwerty", false)
                    ]
                ),
                new ("What is a VPN?", 10,
                    [
                        new ("Virtual Private Network", true),
                        new ("Virtual Public Network", false),
                        new ("Visual Private Network", false),
                        new ("Visual Public Network", false)
                    ]
                ),
                new ("What does HTTPS stand for?", 20,
                    [
                        new ("HyperText Transfer Protocol Secure", true),
                        new ("HyperText Transfer Protocol Simple", false),
                        new ("HyperText Transmission Protocol Secure", false),
                        new ("HyperText Transmission Protocol Simple", false)
                    ]
                )
            ]
        ),
        new ("Shakespeare's Greatest Works",
            [
                new ("Who is the author of 'Hamlet'?", 10,
                    [
                        new ("William Shakespeare", true),
                        new ("Charles Dickens", false),
                        new ("J.K. Rowling", false),
                        new ("Jane Austen", false)
                    ]
                ),
                new ("Which play features the characters Rosencrantz and Guildenstern?", 30,
                    [
                        new ("Hamlet", true),
                        new ("Othello", false),
                        new ("Macbeth", false),
                        new ("King Lear", false)
                    ]
                ),
                new ("What is the setting of 'The Tempest'?", 20,
                    [
                        new ("A remote island", true),
                        new ("Venice", false),
                        new ("Rome", false),
                        new ("Athens", false)
                    ]
                ),
                new ("Which play includes the quote, 'To be, or not to be'?", 10,
                    [
                        new ("Hamlet", true),
                        new ("Macbeth", false),
                        new ("Othello", false),
                        new ("Julius Caesar", false)
                    ]
                )
            ]
        ),
        new ("Astronomy for Beginners",
            [
                new ("What is the closest planet to the Sun?", 10,
                    [
                        new ("Mercury", true),
                        new ("Venus", false),
                        new ("Earth", false),
                        new ("Mars", false)
                    ]
                ),
                new ("What is the largest planet in our solar system?", 20,
                    [
                        new ("Jupiter", true),
                        new ("Saturn", false),
                        new ("Neptune", false),
                        new ("Uranus", false)
                    ]
                ),
                new ("What galaxy is Earth located in?", 30,
                    [
                        new ("Milky Way", true),
                        new ("Andromeda", false),
                        new ("Triangulum", false),
                        new ("Whirlpool", false)
                    ]
                ),
                new ("What is the name of Earth's moon?", 10,
                    [
                        new ("Luna", true),
                        new ("Titan", false),
                        new ("Europa", false),
                        new ("Ganymede", false)
                    ]
                ),
                new ("Who was the first person to walk on the moon?", 20,
                    [
                        new ("Neil Armstrong", true),
                        new ("Buzz Aldrin", false),
                        new ("Yuri Gagarin", false),
                        new ("Michael Collins", false)
                    ]
                )
            ]
        ),
        new ("Modern Art Movements",
            [
                new ("Which art movement is Pablo Picasso known for?", 10,
                    [
                        new ("Cubism", true),
                        new ("Impressionism", false),
                        new ("Surrealism", false),
                        new ("Expressionism", false)
                    ]
                ),
                new ("Who painted 'The Persistence of Memory'?", 20,
                    [
                        new ("Salvador Dalí", true),
                        new ("Vincent van Gogh", false),
                        new ("Claude Monet", false),
                        new ("Henri Matisse", false)
                    ]
                ),
                new ("What is the primary feature of abstract art?", 30,
                    [
                        new ("Lack of recognizable subjects", true),
                        new ("Realistic portrayal", false),
                        new ("Focus on natural landscapes", false),
                        new ("Depiction of everyday life", false)
                    ]
                ),
                new ("Which artist is known for the 'Blue Period'?", 10,
                    [
                        new ("Pablo Picasso", true),
                        new ("Claude Monet", false),
                        new ("Leonardo da Vinci", false),
                        new ("Michelangelo", false)
                    ]
                )
            ]
        ),
        new ("Philosophy 101",
            [
                new ("Who is considered the father of Western philosophy?", 30,
                    [
                        new ("Socrates", true),
                        new ("Plato", false),
                        new ("Aristotle", false),
                        new ("Descartes", false)
                    ]
                ),
                new ("What is the main focus of existentialism?", 10,
                    [
                        new ("Individual freedom and choice", true),
                        new ("Moral values", false),
                        new ("Social structures", false),
                        new ("Religious beliefs", false)
                    ]
                ),
                new ("Who wrote 'Critique of Pure Reason'?", 20,
                    [
                        new ("Immanuel Kant", true),
                        new ("John Locke", false),
                        new ("David Hume", false),
                        new ("Friedrich Nietzsche", false)
                    ]
                ),
                new ("Which philosopher is known for the quote, 'I think, therefore I am'?", 10,
                    [
                        new ("René Descartes", true),
                        new ("Immanuel Kant", false),
                        new ("John Locke", false),
                        new ("Socrates", false)
                    ]
                )
            ]
        ),
        new ("Ultimate Cooking Quiz",
            [
                new ("What is the main ingredient in a soufflé?", 10,
                    [
                        new ("Eggs", true),
                        new ("Flour", false),
                        new ("Sugar", false),
                        new ("Butter", false)
                    ]
                ),
                new ("What is the process of cooking food using steam?", 20,
                    [
                        new ("Steaming", true),
                        new ("Boiling", false),
                        new ("Frying", false),
                        new ("Baking", false)
                    ]
                ),
                new ("Which cuisine is sushi from?", 10,
                    [
                        new ("Japanese", true),
                        new ("Chinese", false),
                        new ("Korean", false),
                        new ("Thai", false)
                    ]
                ),
                new ("What is the main ingredient in guacamole?", 20,
                    [
                        new ("Avocado", true),
                        new ("Tomato", false),
                        new ("Onion", false),
                        new ("Garlic", false)
                    ]
                ),
                new ("What type of pasta is shaped like little ears?", 30,
                    [
                        new ("Orecchiette", true),
                        new ("Fusilli", false),
                        new ("Penne", false),
                        new ("Spaghetti", false)
                    ]
                )
            ]
        ),
        new ("Music Theory Essentials",
            [
                new ("What is the distance between two notes called?", 20,
                    [
                        new ("Interval", true),
                        new ("Chord", false),
                        new ("Scale", false),
                        new ("Melody", false)
                    ]
                ),
                new ("What does 'tempo' refer to in music?", 10,
                    [
                        new ("Speed of the music", true),
                        new ("Pitch of the music", false),
                        new ("Dynamics of the music", false),
                        new ("Harmony of the music", false)
                    ]
                ),
                new ("What is a group of three notes played together called?", 30,
                    [
                        new ("Chord", true),
                        new ("Melody", false),
                        new ("Harmony", false),
                        new ("Scale", false)
                    ]
                ),
                new ("What does a sharp symbol (#) indicate?", 20,
                    [
                        new ("The note is raised by one semitone", true),
                        new ("The note is lowered by one semitone", false),
                        new ("The note is played loudly", false),
                        new ("The note is played softly", false)
                    ]
                ),
                new ("What is the term for gradually getting louder in music?", 10,
                    [
                        new ("Crescendo", true),
                        new ("Decrescendo", false),
                        new ("Fortissimo", false),
                        new ("Pianissimo", false)
                    ]
                )
            ]
        ),
        new ("Environmental Science Facts",
            [
                new ("What is the process by which plants make their food?", 10,
                    [
                        new ("Photosynthesis", true),
                        new ("Respiration", false),
                        new ("Transpiration", false),
                        new ("Digestion", false)
                    ]
                ),
                new ("What is the main cause of global warming?", 30,
                    [
                        new ("Greenhouse gases", true),
                        new ("Deforestation", false),
                        new ("Ozone layer depletion", false),
                        new ("Air pollution", false)
                    ]
                ),
                new ("Which is the most abundant gas in the Earth's atmosphere?", 20,
                    [
                        new ("Nitrogen", true),
                        new ("Oxygen", false),
                        new ("Carbon Dioxide", false),
                        new ("Argon", false)
                    ]
                ),
                new ("What is the main source of energy for the Earth's climate system?", 10,
                    [
                        new ("The Sun", true),
                        new ("The Moon", false),
                        new ("The Earth's core", false),
                        new ("The Oceans", false)
                    ]
                ),
                new ("What is the term for the variety of life in the world or in a particular habitat?", 20,
                    [
                        new ("Biodiversity", true),
                        new ("Ecology", false),
                        new ("Ecosystem", false),
                        new ("Biome", false)
                    ]
                )
            ]
        ),
        new ("Space Exploration Trivia",
            [
                new ("Who was the first person to walk on the moon?", 10,
                    [
                        new ("Neil Armstrong", true),
                        new ("Buzz Aldrin", false),
                        new ("Yuri Gagarin", false),
                        new ("Michael Collins", false)
                    ]
                ),
                new ("What is the name of the first artificial satellite?", 20,
                    [
                        new ("Sputnik 1", true),
                        new ("Apollo 11", false),
                        new ("Voyager 1", false),
                        new ("Hubble", false)
                    ]
                ),
                new ("What planet is known as the Red Planet?", 10,
                    [
                        new ("Mars", true),
                        new ("Venus", false),
                        new ("Jupiter", false),
                        new ("Saturn", false)
                    ]
                ),
                new ("What is the largest planet in our solar system?", 30,
                    [
                        new ("Jupiter", true),
                        new ("Saturn", false),
                        new ("Neptune", false),
                        new ("Uranus", false)
                    ]
                ),
                new ("What is the nearest star to Earth?", 20,
                    [
                        new ("The Sun", true),
                        new ("Proxima Centauri", false),
                        new ("Sirius", false),
                        new ("Alpha Centauri", false)
                    ]
                )
            ]
        ),
        new ("Literary Classics Quiz",
            [
                new ("Who wrote 'Pride and Prejudice'?", 10,
                    [
                        new ("Jane Austen", true),
                        new ("Charlotte Brontë", false),
                        new ("Emily Brontë", false),
                        new ("George Eliot", false)
                    ]
                ),
                new ("What is the main theme of 'Moby Dick'?", 30,
                    [
                        new ("Obsession", true),
                        new ("Friendship", false),
                        new ("Love", false),
                        new ("Revenge", false)
                    ]
                ),
                new ("Who is the author of '1984'?", 20,
                    [
                        new ("George Orwell", true),
                        new ("Aldous Huxley", false),
                        new ("Ray Bradbury", false),
                        new ("Kurt Vonnegut", false)
                    ]
                ),
                new ("Which novel starts with 'Call me Ishmael'?", 10,
                    [
                        new ("Moby Dick", true),
                        new ("War and Peace", false),
                        new ("Great Expectations", false),
                        new ("The Odyssey", false)
                    ]
                ),
                new ("Who wrote 'To Kill a Mockingbird'?", 20,
                    [
                        new ("Harper Lee", true),
                        new ("Mark Twain", false),
                        new ("F. Scott Fitzgerald", false),
                        new ("Ernest Hemingway", false)
                    ]
                )
            ]
        ),
        new ("Cryptography and Security",
            [
                new ("What is the primary purpose of cryptography?", 30,
                    [
                        new ("Secure communication", true),
                        new ("Data storage", false),
                        new ("File compression", false),
                        new ("Internet browsing", false)
                    ]
                ),
                new ("Which algorithm is known as the public-key cryptography?", 20,
                    [
                        new ("RSA", true),
                        new ("SHA-256", false),
                        new ("MD5", false),
                        new ("AES", false)
                    ]
                ),
                new ("What is a common use of hash functions?", 10,
                    [
                        new ("Password storage", true),
                        new ("Encrypting emails", false),
                        new ("Compressing files", false),
                        new ("Securing web traffic", false)
                    ]
                ),
                new ("What does the acronym VPN stand for?", 10,
                    [
                        new ("Virtual Private Network", true),
                        new ("Virtual Public Network", false),
                        new ("Virtual Protected Network", false),
                        new ("Virtual Personal Network", false)
                    ]
                ),
                new ("What is a man-in-the-middle attack?", 20,
                    [
                        new ("An attack where the attacker secretly intercepts and relays messages between two parties", true),
                        new ("An attack where the attacker sends multiple requests to overwhelm a server", false),
                        new ("An attack where the attacker modifies the content of a message", false),
                        new ("An attack where the attacker uses a phishing email to gain credentials", false)
                    ]
                )
            ]
        ),
        new ("Essential Business Strategies",
            [
                new ("What is SWOT analysis?", 30,
                    [
                        new ("A strategic planning tool", true),
                        new ("A financial statement", false),
                        new ("A marketing strategy", false),
                        new ("An organizational chart", false)
                    ]
                ),
                new ("What does KPI stand for?", 20,
                    [
                        new ("Key Performance Indicator", true),
                        new ("Key Product Index", false),
                        new ("Knowledge Process Information", false),
                        new ("Key Process Integration", false)
                    ]
                ),
                new ("What is market segmentation?", 10,
                    [
                        new ("Dividing a market into distinct groups of buyers", true),
                        new ("Analyzing competitors", false),
                        new ("Setting product prices", false),
                        new ("Creating a marketing plan", false)
                    ]
                ),
                new ("What is a value proposition?", 20,
                    [
                        new ("A statement that explains how a product solves a problem", true),
                        new ("A financial projection", false),
                        new ("A marketing tactic", false),
                        new ("A company's mission statement", false)
                    ]
                ),
                new ("What is a business model canvas?", 30,
                    [
                        new ("A strategic management tool to develop new or existing business models", true),
                        new ("A framework for digital marketing", false),
                        new ("A financial analysis tool", false),
                        new ("A customer segmentation method", false)
                    ]
                )
            ]
        ),
        new ("Medical Terminology Basics",
            [
                new ("What does the prefix 'cardio-' refer to?", 10,
                    [
                        new ("Heart", true),
                        new ("Lung", false),
                        new ("Liver", false),
                        new ("Kidney", false)
                    ]
                ),
                new ("What does 'neurology' study?", 30,
                    [
                        new ("Nervous system", true),
                        new ("Digestive system", false),
                        new ("Circulatory system", false),
                        new ("Endocrine system", false)
                    ]
                ),
                new ("What is the medical term for high blood pressure?", 20,
                    [
                        new ("Hypertension", true),
                        new ("Hypotension", false),
                        new ("Hyperlipidemia", false),
                        new ("Hypoglycemia", false)
                    ]
                ),
                new ("What is the medical term for low blood sugar?", 10,
                    [
                        new ("Hypoglycemia", true),
                        new ("Hyperglycemia", false),
                        new ("Hypotension", false),
                        new ("Hypertension", false)
                    ]
                ),
                new ("What does 'dermatology' focus on?", 20,
                    [
                        new ("Skin", true),
                        new ("Heart", false),
                        new ("Lungs", false),
                        new ("Bones", false)
                    ]
                )
            ]
        )
    ];
}
